SELECT 
    COUNT(*) AS total_linhas,
    COUNT(*) - COUNT(numero_empenho) AS nulos_numero_empenho,
    COUNT(*) - COUNT(data_empenho) AS nulos_data_empenho,
    COUNT(*) - COUNT(mes) AS nulos_valor_mes,
    COUNT(*) - COUNT(codigo_unidade_gestora) AS nulos_codigo_unidade_gestora, 
    COUNT(*) - COUNT(codigo_unidade_orcamentaria) AS nulos_codigo_unidade_orcamentaria,
    COUNT(*) - COUNT(cpf_cnpj) AS nulos_cpf_cnpj,
    COUNT(*) - COUNT(codigo_funcao) AS nulos_codigo_funcao,
    COUNT(*) - COUNT(codigo_subfuncao) AS nulos_valor_empenhado,
    COUNT(*) - COUNT(codigo_programa) AS nulos_codigo_programa,
    COUNT(*) - COUNT(codigo_acao) AS nulos_codigo_acao,
    COUNT(*) - COUNT(codigo_categoria_economica) AS nulos_codigo_categoria_economica,
    COUNT(*) - COUNT(codigo_natureza) AS nulos_codigo_natureza,
    COUNT(*) - COUNT(codigo_modalidade_aplicacao) AS nulos_codigo_modalidade_aplicacao,
    COUNT(*) - COUNT(codigo_elemento_despesa) AS nulos_codigo_elemento_despesa,
    COUNT(*) - COUNT(codigo_subelemento) AS nulos_codigo_subelemento,
    COUNT(*) - COUNT(codigo_subelemento_exibicao) AS nulos_codigo_subelemento_exibicao,
    COUNT(*) - COUNT(codigo_fonte_recurso) AS nulos_codigo_fonte_recurso,
    COUNT(*) - COUNT(co) AS nulos_co,
    COUNT(*) - COUNT(numero_licitacao) AS nulos_numero_licitacao,
    COUNT(*) - COUNT(modalidade_licitacao) AS nulos_modalidade_licitacao,
    COUNT(*) - COUNT(numero_obra) AS nulos_numero_obra,
    COUNT(*) - COUNT(valor_empenhado) AS nulos_valor_empenhado,
    COUNT(*) - COUNT(valor_liquidado) AS nulos_valor_liquidado,
    COUNT(*) - COUNT(valor_pago) AS nulos_valor_pago,
    COUNT(*) - COUNT(historico) AS nulos_historico,
    COUNT(*) - COUNT(ano_fonte) AS nulos_ano_fonte
FROM fato_empenhos;