-- MySQL Script generated by MySQL Workbench
-- Sat Sep 12 19:41:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema modelagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelagem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `modelagem` ;

-- -----------------------------------------------------
-- Table `modelagem`.`dim_acao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_acao` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_acao` (
  `codigo_acao` BIGINT NOT NULL,
  `acao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_acao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_categoria_economica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_categoria_economica` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_categoria_economica` (
  `codigo_categoria_economica` BIGINT NOT NULL,
  `categoria_economica` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_categoria_economica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_co`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_co` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_co` (
  `co` DOUBLE NOT NULL,
  `descricao_co` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`co`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_credor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_credor` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_credor` (
  `cpf_cnpj` BIGINT NOT NULL,
  `nome_credor` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cpf_cnpj`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_elemento_despesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_elemento_despesa` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_elemento_despesa` (
  `codigo_elemento_despesa` BIGINT NOT NULL,
  `elemento_despesa` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_elemento_despesa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_fonte_recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_fonte_recurso` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_fonte_recurso` (
  `codigo_fonte_recurso` BIGINT NOT NULL,
  `descricao_fonte_recurso` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_fonte_recurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_funcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_funcao` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_funcao` (
  `codigo_funcao` BIGINT NOT NULL,
  `funcao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_funcao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_modalidade_aplicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_modalidade_aplicacao` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_modalidade_aplicacao` (
  `codigo_modalidade_aplicacao` BIGINT NOT NULL,
  `modalidade_aplicacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_modalidade_aplicacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_natureza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_natureza` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_natureza` (
  `codigo_natureza` BIGINT NOT NULL,
  `grupo_natureza_despesa` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_natureza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_programa` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_programa` (
  `codigo_programa` BIGINT NOT NULL,
  `programa` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_programa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_subfuncao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_subfuncao` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_subfuncao` (
  `codigo_subfuncao` BIGINT NOT NULL,
  `subfuncao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_subfuncao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_unidade_gestora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_unidade_gestora` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_unidade_gestora` (
  `codigo_unidade_gestora` DOUBLE NOT NULL,
  `descricao_unidade_gestora` TEXT NULL DEFAULT NULL,
  `municipio` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_unidade_gestora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`dim_unidade_orcamentaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`dim_unidade_orcamentaria` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`dim_unidade_orcamentaria` (
  `codigo_unidade_orcamentaria` BIGINT NOT NULL,
  `descricao_unidade_orcamentaria` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_unidade_orcamentaria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `modelagem`.`fato_empenhos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelagem`.`fato_empenhos` ;

CREATE TABLE IF NOT EXISTS `modelagem`.`fato_empenhos` (
  `id_fato` BIGINT NOT NULL AUTO_INCREMENT,
  `numero_empenho` BIGINT NULL,
  `data_empenho` DATETIME NULL DEFAULT NULL,
  `mes` TEXT NULL DEFAULT NULL,
  `codigo_unidade_gestora` DOUBLE NULL,
  `codigo_unidade_orcamentaria` BIGINT NULL DEFAULT NULL,
  `cpf_cnpj` BIGINT NULL DEFAULT NULL,
  `codigo_funcao` BIGINT NULL DEFAULT NULL,
  `codigo_subfuncao` BIGINT NULL DEFAULT NULL,
  `codigo_programa` BIGINT NULL DEFAULT NULL,
  `codigo_acao` BIGINT NULL DEFAULT NULL,
  `codigo_categoria_economica` BIGINT NULL DEFAULT NULL,
  `codigo_natureza` BIGINT NULL DEFAULT NULL,
  `codigo_modalidade_aplicacao` BIGINT NULL DEFAULT NULL,
  `codigo_elemento_despesa` BIGINT NULL DEFAULT NULL,
  `codigo_subelemento` BIGINT NULL DEFAULT NULL,
  `codigo_subelemento_exibicao` TEXT NULL DEFAULT NULL,
  `codigo_fonte_recurso` BIGINT NULL DEFAULT NULL,
  `co` DOUBLE NULL DEFAULT NULL,
  `numero_licitacao` BIGINT NULL DEFAULT NULL,
  `modalidade_licitacao` TEXT NULL DEFAULT NULL,
  `numero_obra` BIGINT NULL DEFAULT NULL,
  `valor_empenhado` DOUBLE NULL DEFAULT NULL,
  `valor_liquidado` DOUBLE NULL DEFAULT NULL,
  `valor_pago` DOUBLE NULL DEFAULT NULL,
  `historico` TEXT NULL DEFAULT NULL,
  `ano_fonte` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_fato`),
  INDEX `fk_fato_credor_idx` (`cpf_cnpj` ASC) VISIBLE,
  INDEX `fk_fato_ug_idx` (`codigo_unidade_gestora` ASC) VISIBLE,
  INDEX `fk_fato_uo_idx` (`codigo_unidade_orcamentaria` ASC) VISIBLE,
  INDEX `fk_fato_funcao_idx` (`codigo_funcao` ASC) VISIBLE,
  INDEX `fk_fato_subfuncao_idx` (`codigo_subfuncao` ASC) VISIBLE,
  INDEX `fk_fato_programa_idx` (`codigo_programa` ASC) VISIBLE,
  INDEX `fk_fato_acao_idx` (`codigo_acao` ASC) VISIBLE,
  INDEX `fk_fato_categoria_idx` (`codigo_categoria_economica` ASC) VISIBLE,
  INDEX `fk_fato_natureza_idx` (`codigo_natureza` ASC) VISIBLE,
  INDEX `fk_fato_modalidade_idx` (`codigo_modalidade_aplicacao` ASC) VISIBLE,
  INDEX `fk_fato_elemento_idx` (`codigo_elemento_despesa` ASC) VISIBLE,
  INDEX `fk_fato_fonte_idx` (`codigo_fonte_recurso` ASC) VISIBLE,
  INDEX `fk_fato_co_idx` (`co` ASC) VISIBLE,
  CONSTRAINT `fk_fato_credor`
    FOREIGN KEY (`cpf_cnpj`)
    REFERENCES `modelagem`.`dim_credor` (`cpf_cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_ug`
    FOREIGN KEY (`codigo_unidade_gestora`)
    REFERENCES `modelagem`.`dim_unidade_gestora` (`codigo_unidade_gestora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_uo`
    FOREIGN KEY (`codigo_unidade_orcamentaria`)
    REFERENCES `modelagem`.`dim_unidade_orcamentaria` (`codigo_unidade_orcamentaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_funcao`
    FOREIGN KEY (`codigo_funcao`)
    REFERENCES `modelagem`.`dim_funcao` (`codigo_funcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_subfuncao`
    FOREIGN KEY (`codigo_subfuncao`)
    REFERENCES `modelagem`.`dim_subfuncao` (`codigo_subfuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_programa`
    FOREIGN KEY (`codigo_programa`)
    REFERENCES `modelagem`.`dim_programa` (`codigo_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_acao`
    FOREIGN KEY (`codigo_acao`)
    REFERENCES `modelagem`.`dim_acao` (`codigo_acao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_categoria`
    FOREIGN KEY (`codigo_categoria_economica`)
    REFERENCES `modelagem`.`dim_categoria_economica` (`codigo_categoria_economica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_natureza`
    FOREIGN KEY (`codigo_natureza`)
    REFERENCES `modelagem`.`dim_natureza` (`codigo_natureza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_modalidade`
    FOREIGN KEY (`codigo_modalidade_aplicacao`)
    REFERENCES `modelagem`.`dim_modalidade_aplicacao` (`codigo_modalidade_aplicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_elemento`
    FOREIGN KEY (`codigo_elemento_despesa`)
    REFERENCES `modelagem`.`dim_elemento_despesa` (`codigo_elemento_despesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_co`
    FOREIGN KEY (`co`)
    REFERENCES `modelagem`.`dim_co` (`co`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_fonte`
    FOREIGN KEY (`codigo_fonte_recurso`)
    REFERENCES `modelagem`.`dim_fonte_recurso` (`codigo_fonte_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
